### ISSUE TITLE
Port to Python3 and Qt5 + others

### ISSUE THREAD

**Issue by beville** [davide-romanini/comictagger#108]
Hey there,

Not an issue, more of a pull suggestion :-)

Just wanted to let you know that I did bit of work on a branch over here: https://github.com/beville/comictagger

I started off just wanting to get the setup.py installer working again, and ending up doing a port to Python3 and PyQt5, neither of which was very much work. 

I also added configuration for the unrar library to the GUI and the settings.  Not an issue for the binary distros, but handy if you're just running form source.  

If you're interested in merging, let me know, and I'll help if I can.  If not, no worries!

More details are on the README at the "py3qt5_dev" branch.  

Thanks for all the work you've done on this project!

**Comment by davide-romanini** [comment]
@beville You should already have push access to the main repo, so feel free to push the new branch there :-)

**Comment by davide-romanini** [comment]
I pushed the new branch here and updated the windows build script used by appveyor: upgrading to python3 and qt5 is definitely a life saver. Here's the latest build: https://ci.appveyor.com/project/davide-romanini/comictagger/build/1.0.39/artifacts

I still have some problems though:
 - the windows build made with pyinstaller seems to use a vintage qt theme from the 90's.. Maybe it's related to this pyinstaller issue, https://github.com/pyinstaller/pyinstaller/pull/3439 I need to double check. It doesn't happen when launching locally with python.
 - reading rars doesn't work out of the box (it works when launghing locally with python)
 - there's that nasty problem reading images behind ssl

After solving these problems I hope to merge to whole thing into develop and create a new release.

**Comment by beville** [comment]
Cool.

Sounds like you are seeing the same style problem under Windows that I saw on my Mac.  It was definitely solved by getting a pre-release of pyinstaller as referenced in the answer here: https://stackoverflow.com/questions/48626999/packaging-with-pyinstaller-pyqt5-setstyle-ignored.   I didn't need to do anything special on Windows, though, just generic pip installs. Unfortunately, my windows laptop is at the repair shop now, so I can't reference it.
------------
With respect to your unrar issue:  I never actually never got my Windows mingw libunrar build working, so just worked around it with my brief attempt at the Windows pyinstaller build. 
 
The new settings tab for RAR will hide the unrar library selection GUI controls if the app finds libunrar.so in the comictagger module folder (or in sys._MEIPASS in the case of the bundled exe). So if you do see those GUI controls, that means that that file isn't there in the exe.   Based on the your original code that looks for the library, I was assuming that even under Windows, the binary file will be called "libunrar.so".  Is that still correct?  Hopefully this helps, and it's something simple!

**Comment by davide-romanini** [comment]
I finally merged the branch in develop. I also released a windows version. Unfortunately I don't have access to a mac anymore, so I cannot build and test the osx version. I think we're making some little progress, so I close this one at least. Thanks for your work.
