### ISSUE TITLE
"Could not connect to comic vine to search for series"

### ISSUE THREAD

**Issue by kabutocub** [davide-romanini/comictagger#110]
I'm using the ComicTagger-1.1.20+py3qt5.dev build for windows. 

I'm able to tag many other comics, but if I try to tag any Superman comics (for example) it starts searching... sometimes it pops up the error window after just a second, sometimes it can get to 50 percent or more before doing it. Like its timing out? Maybe? Not sure if its me or what. My API is good, internet is fine, so yeah not sure.

**Comment by jjpare** [comment]
Just started happening to me as well — any book that takes more than a few seconds to search for will end up timing out with this error.

**Comment by bpepple** [comment]
I believe this is due to a problem on Comic Vine's end and not comictagger's, since I'm getting some HTTP 502 Errors while querying.

**Comment by bpepple** [comment]
Looks like Comic Vine rolled out a new website today, so most likely that's the cause for the http error timeouts occurring. You might want to check if your problem still exists.

**Comment by davide-romanini** [comment]
I think it's no more an issue.
