### ISSUE TITLE
tag save operation seemed to fail

### ISSUE THREAD

**Issue by Ruby74** [davide-romanini/comictagger#113]
Hi there,
is this project still active? I am using the latest version of both Comictagger and Winrar.
I tried 32 and 64 bit version of winrar, but saving tags to cbr files results in:
The tag save operation seemed to fail.
Can anyone help? Am I doing something wrong?

Greetings
Marco

**Comment by davide-romanini** [comment]
It seem related to `subprocess` usage inside pyinstaller. I'm checking it out.

**Comment by davide-romanini** [comment]
Try with latest [pre release 1.1.30-rc1](https://github.com/davide-romanini/comictagger/releases/tag/1.1.30-rc1)

**Comment by Ruby74** [comment]
Writing tags to cbr archive is working now. Thank you. However, choosing "search online", or "auto-identify" leads to error: Could not connect to comicvine to search for series.

**Comment by gramster** [comment]
cbr tagging doesn't work for me; cbz works fine.

**Comment by davide-romanini** [comment]
Closing the issue since the specific problem seems to be solved.

**Comment by AlanDunaway** [comment]
Still happening.
