### ISSUE TITLE
Why does the CLI version require macOS ≥10.12?

### ISSUE THREAD

**Issue by elmimmo** [davide-romanini/comictagger#116]
When trying to launch the app from the command line I get:

```
$ /Applications/ComicTagger.app/Contents/MacOS/ComicTagger 
Error loading Python lib '/Applications/ComicTagger.app/Contents/MacOS/.Python': dlopen(/Applications/ComicTagger.app/Contents/MacOS/.Python, 10): Symbol not found: _getentropy
  Referenced from: /Applications/ComicTagger.app/Contents/MacOS/.Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/ComicTagger.app/Contents/MacOS/.Python
```

Why was the binary built specifically for Mac OS X 10.12? Maybe [this](https://github.com/ma1co/Sony-PMCA-RE/issues/55) is relevant?

I am running macOS 10.11.6 and installed comictagger via `homebrew cask install comictagger`.

**Comment by davide-romanini** [comment]
Yes, I'm starting to use Travis CI to build osx images (I don't own a mac). As far as I remember 10.12 was the oldest version that actually worked successfully, after many tries. If someone can provide a more compatible working travis configuration, it will be appreciated.
