### ISSUE TITLE
Comic Vine search results have changed

### ISSUE THREAD

**Issue by beville** [davide-romanini/comictagger#117]
It seems that this week Comic Vine has changed the way search results work again.

Whereas before the all the search terms for a volume title were required (ANDed together), now there results only require one of the terms to match (ORed together).  So a search for "Luthor Strode" will match "Lex Luthor", example.  This means that the more words in a volume title, the more hits!  Every search is resulting in scores or more of search page fetches.

There is a request at the Comic Vine AP forums [here](https://comicvine.gamespot.com/forums/api-developers-2334/recent-search-query-changes-1990598/)  for info on how to do the exclusive searching again.

The good news is that results seem to be sorted by relevance, so I'm experimenting with limiting the search requests with a few new checks:

1. If there are a number of search terms, the best matches appear first, so by checking the last match of a "page" of results, if any of the terms aren't present, we can probably safely assume that we can stop request new search pages
2. For shorter titles, we can probably stop searching once the word count in the results get too large. For example for the search term "Batman" (N=1), we can safely stop searching probably once the result titles have  N+2 (N+3?) words in them.

I'm going to start experimenting, and will probably have a pull request next week.

**Comment by gramster** [comment]
I was wondering what happened. With the huge number of results being pulled down its also really easy to fail due to rate limiting. 

It seems to me that auto-identify is not as adversely impacted as auto-tag but I may be wrong.

**Comment by jdinda70** [comment]
@beville Thank you!  works great!

**Comment by casperOne** [comment]
The algorithm seems like a strong start, but as a quick patch, it would be great if we could specify in the settings (or tag dialog) the maximum number of pages of results to process.

I'd like to be able to default to a maximum number of pages in the event the algorithm hits a snag.

**Comment by davide-romanini** [comment]
Merged on develop, closing.
