### ISSUE TITLE
Volume number not pulled from ComicVine

### ISSUE THREAD

**Issue by garrettjj** [davide-romanini/comictagger#122]
I'm not sure whether this is an intended behavior or not but whenever I pull tags from ComicVine, the volume (start_year in API) doesn't seem to get pulled correctly. Expected behavior would be similar to other clients where the volume number is pulled as it is stored by ComicVine with the start_year value being saved into the metadata file.

If you require any further information, please let me know. If anyone else has any ideas for threads to pull to remedy this, also let me know. A bit rough on programming but can potentially spend a day following the data through the program to find out why start_year comes in and doesn't get out.

**Comment by davide-romanini** [comment]
According to [this line of code](https://github.com/davide-romanini/comictagger/blob/91f82fd6d37636b3f7d7566bb01ae58ebf7d5ea4/comictaggerlib/comicvinetalker.py#L469) there's a setting `use_series_start_as_volume` to force the wanted behaviour.

**Comment by garrettjj** [comment]
Ah, thanks a ton! Such a dumb thing :)
