### ISSUE TITLE
Error When Searching ComicVine

### ISSUE THREAD

**Issue by jcal22** [davide-romanini/comictagger#136]
ComicVine stopped responding to searches.  Console shows the following error:

<urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1056)>

**Comment by jcal22** [comment]
Already solved!

**Comment by omgthegreenranger** [comment]
How did you solve it? I'm getting that error when I try to search, and testing my key gives me an invalid key notification. Yet, I can use the API key on browser searches.
