### ISSUE TITLE
Possible drag & drop issue on MacOS

### ISSUE THREAD

**Issue by beville** [davide-romanini/comictagger#142]
I'm not sure if this is still an issue, since I don't have a Mac anymore, and haven't had an up-to-date Mac for years, but I wanted to document a potential fix that I have some notes on.  If it's not currently a problem, go ahead and close.

Essentially, there is some very Mac specific code for handling drag and drop that I had found wasn't still needed (and maybe was crash-inducing).  Specifically, there is a function in taggerwindows.py:

```
    def getUrlFromLocalFileID(self, localFileID):
        import sys
        if not sys.platform == 'darwin':
            return localFileID.toLocalFile()

        import objc
        import CoreFoundation as CF
        localFileQString = QString(localFileID.toLocalFile())
        relCFStringRef = CF.CFStringCreateWithCString(
            CF.kCFAllocatorDefault,
            localFileQString.toUtf8(),
            CF.kCFStringEncodingUTF8
            )
        relCFURL = CF.CFURLCreateWithFileSystemPath(
            CF.kCFAllocatorDefault,
            relCFStringRef,
            CF.kCFURLPOSIXPathStyle,
            False  # is directory
            )
        absCFURL = CF.CFURLCreateFilePathURL(
            CF.kCFAllocatorDefault,
            relCFURL,
            objc.NULL
            )

        local = QUrl(str(absCFURL[0])).toLocalFile()
        
        return local
```
If there are still issues, try testing without the special code, and just have this:

```
    def getUrlFromLocalFileID(self, localFileID):
        return localFileID.toLocalFile()
```
I have no way to test this anymore, so if this is found to be erroneous, please close.  :-)

**Comment by davide-romanini** [comment]
Yes, it's definitely a problem, it crashes horribly whenever I drag a file on the window. I rented a macincloud instance just to do some testing, I'll check it out for sure.
Thanks for the suggestion. 👍

**Comment by davide-romanini** [comment]
I tested the fix on macos mojave and it seem to work. Will be in next release. Thanks!
