### ISSUE TITLE
CBR files give "No Comic Archives were Found."

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#49]
_From [carterar...@gmail.com](https://code.google.com/u/104289333623573579620/) on April 10, 2014 16:16:37_

What version of ComicTagger are you using? ComicTagger v1.1.13-beta On what operating system (Mac, Linux, Windows)? What version? Mac GUI or command line? GUI What steps will reproduce the problem? 1.Drag CBR files or try to bring in CBR files 2. 3. What is the expected output? What do you see instead? I got a warning: "No Comic Archives were Found." Please provide any additional information below.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=49_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on April 10, 2014 10:30:42_

Did you configure the unrar program executable in the settings? https://code.google.com/p/comictagger/wiki/UserGuide#RAR_Tools

**Comment by tikilab** [comment]
Since he didn't answer, I will. Yes, I did. Still having this issue.

**Comment by davide-romanini** [comment]
Closing.
