### ISSUE TITLE
Can't set credit information via the command line

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#56]
_From [wyldph...@gmail.com](https://code.google.com/u/112925390010469244217/) on August 07, 2014 15:11:35_

What version of ComicTagger are you using? 1.1.15-beta On what operating system (Mac, Linux, Windows)? What version? Mac, OS X 10.9.4 GUI or command line? Command Line What steps will reproduce the problem? 1. Try the following 
ComicTagger -s -t cr -m "credit: Penciller: ArtistName" Test.cbz
2. Get an error 
ValueError: need more than 1 value to unpack What is the expected output? What do you see instead? From reading the documentation I get the impression that it's not possible to set information like the credits from the command line. It would be great if support could be expanded to make this possible, as setting this information manually in the GUI for more than a handful of files is really annoying. Please provide any additional information below.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=56_

**Comment by goodevilgenius** [comment]
Try `comictagger -s -t cr -m "credit=Peniciller:ArtistName" Test.cbz`. Works fine.

**Comment by davide-romanini** [comment]
Closing.
