### ISSUE TITLE
Is there a beta version for support with Yosemite?

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#57]
_From [antonios...@gmail.com](https://code.google.com/u/108116382160330488426/) on August 11, 2014 17:02:04_

What version of ComicTagger are you using? 1.1.15-beta

On what operating system (Mac, Linux, Windows)? What version? Mac OS 10.10

GUI or command line? GUI

I am sure you are undoubtedly aware that it currently doesn't support Yosemite Sam as when comic files are tired to be imported they are met with the error message - No comic archives were found.

Is there a workaround, a new beta, or an expected date for release?

Thanking you.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=57_

**Comment by eduo** [comment]
While not a fix, I wonder if this issue is actually current, since I use this same version in Yosemite without any issues. Also El Capitan Beta.

**Comment by davide-romanini** [comment]
Old. Hoping to support more platforms with build automation. Closing.
