### ISSUE TITLE
Can't make it work with the new changes in unrar library 

### ISSUE THREAD

**Issue by fcanc** [davide-romanini/comictagger#72]
I followed the instructions and downloaded the source from the [RARLab Download](http://www.rarlab.com/rar_add.htm) page, I then ran `make lib` and `make install-lib` and of course `pip install unrar`, but when I run comictagger.py it gives a LookupError "Couldn't find path to unrar library".
Then I tried to install unrar with MacPorts `sudo port install unrar` with no changes.
What is the proper method to set `UNRAR_LIB_PATH` in the environment?
And should it point to the path where the binary is installed?

**Comment by fcanc** [comment]
I noticed that make install-lib installs a file named libunrar.so in the path /usr/lib/ but unrarlib.py looks for a file named unrar (like the binary):

```python
# find and load unrar library
unrarlib = None
if platform.system() == 'Windows':
### CUT
else:
    # assume unix
   ### CUT
    lib_path = lib_path or find_library("unrar")
    if lib_path:
        unrarlib = ctypes.cdll.LoadLibrary(lib_path)

if unrarlib is None:
    raise LookupError("Couldn't find path to unrar library.")
```

**Comment by davide-romanini** [comment]
I think that find_library uses a platform specific search algorithm, even on linux the name unrar resolves to libunrar.so, don't know how does it on the mac. Try starting comictagger with:
```
  $ UNRAR_LIB_PATH=/usr/lib/libunrar.so comictagger.py

```
and see what it does.

**Comment by matiasb** [comment]
Right, as @davide-romanini pointed out, find_library takes a name and automatically tries to find the library (in the expected paths, system dependent), as stated in the linked documentation. You can also force a specific path by setting the UNRAR_LIB_PATH env variable (as shown above).
So the real issue seems to be libunrar.so is not located in a path where dynamic libraries are being searched for.

**Comment by fcanc** [comment]
According to the ctypes documentation `find_library` searches by prefixing `lib` in the given name and postfixing the proper extension for the os in use, that's `.so` for Linux and `.dylib` for OS X.
But the unrar makefile installs using the linux ext no matter what's the system being used.
I believe renaming my installed file to `libunrar.dylib` should be safe in this case.
Thanks for the tips!

**Comment by davide-romanini** [comment]
Ok, so it seems more an issue for the unrar source makefile, that sadly isn't on github :-( I'll update the readme adding the tip, while thinking of a better way to package this stuff in a more practical way.

**Comment by fcanc** [comment]
I noticed that requirements.txt is using `-e git+https://github.com/matiasb/python-unrar.git@1010cf5f6fcf09a9b1fe7c958faf0167fafaa7d9#egg=unrar-master` instead of the standard `$ pip install unrar` reported in the [package page](https://pypi.python.org/pypi/unrar/) (which I used), why using the repository instead?

**Comment by davide-romanini** [comment]
It was temporary, now it should point to last 0.3 version of unrar.
Il giorno 22/Feb/2015 14:33, "fcanc" <notifications@github.com> ha scritto:

**Comment by davide-romanini** [comment]
Updated in 68030a102433035b6e72b0e573e62efcb75d07f0

**Comment by liquefry** [comment]
I note that this is closed, but have just installed on Fedora and this error still seems present.  I installed libunrar using the instructions from python-unrar, and I now have libunrar.so in /usr/lib but comictagger can't find it.  If I specify the library in the command line comictagger works... is this still on the list to be fixed?

**Comment by davide-romanini** [comment]
Mmh, I still run using the env variable in development. I think we shouldn't rely on a system level installation of the library, but decide a known place at build time and use it. I'd like to integrate the full compilation step in the various platform-specific build script but still didn't have much time for improvements in this area..

**Comment by rafaelrizzatti** [comment]
You can also do the follow command:
export UNRAR_LIB_PATH=/usr/local/bin/libunrar.so
(Can be: **/usr/lib/libunrar.so**  too, verify your path)
And after execute the Python File
