### ISSUE TITLE
Enhancement: Support for store_date

### ISSUE THREAD

**Issue by tahngarth** [davide-romanini/comictagger#77]
In the comicvine api they support the store_date data, which I know is at least supported by ComicRack. It would be great if comictagger could support this so I can stop using the comicvine scraper plugin for ComicRack.

**Comment by tahngarth** [comment]
Nevermind, it's not in the xml schema, this is stored in the CR database. Drat.

**Comment by anoma** [comment]
Seems relevant

https://github.com/davide-romanini/comictagger/issues/76
