### ISSUE TITLE
Meeting dependencys Ubuntu

### ISSUE THREAD

**Issue by anoma** [davide-romanini/comictagger#80]
We could do with some updated, fork specific, install instructions.

Specifically what is the correct procedure for Ubuntu natsort dependency.

> pip install natsort

whilst successful still results in:

> ImportError: No module named natsort

For reference so far I have:

> apt-get install python-qt4 python-imaging python-bs4
> pip install configparser
> pip install natsort

although it is not clear if i even need all of these for a CLI only install and ideally we shouldn't mix apt and pip unless we need to.

Also google yields install instructions that pull CT form pip which obviously is not ideal for users trying to complete this fork install (which IMO is the only version they should install)

**Comment by davide-romanini** [comment]
I usually follow this steps:
 - install [`virtualenv`](https://virtualenv.pypa.io/en/latest/installation.html)
 - install python-qt4 (`apt-get install python-qt4`)
 - `virtualenv --system-site-packages venv`
 - `pip install -r requirements.txt`
 - run comictagger
I still need to configure also unrar.. Maybe I could just copy the same paver script I introduced in comicstreamer to automate that boring part.. I'd really love if people just stops using cbr so I can trash all that stuff :-D

**Comment by rv10guy** [comment]
I still have trouble related to unrar. I get the following when I follow your instructions under Ubuntu 16.04:

```
  File "/home/scott/.local/lib/python2.7/site-packages/unrar/unrarlib.py", line 57, in <module>
    raise LookupError("Couldn't find path to unrar library.")
LookupError: Couldn't find path to unrar library.
```

**Comment by davide-romanini** [comment]
Closing. Hoping to automate binary releases very soon.
