### ISSUE TITLE
Online search : no matches found!

### ISSUE THREAD

**Issue by toto8551** [davide-romanini/comictagger#97]
During online search, often I get the "no matches found!" message.

Example : I search a comic with the series name : "Ultimate Spider-Man", I got "no matches found!".
On the comic vine web site, I know that series exists : [here](https://comicvine.gamespot.com/ultimate-spider-man/4050-27381/), and the search should give me many results.

If I search "Ultimate", then I can pick up the comic I am looking for. But even with all the data from comicvine inside the details tab, if I do the online search, I still got "no matches found!" ???

I am running comictagger under debian/linux.

edit : sounds that's not a comictagger bug, but a comicvine one : [link](https://comicvine.gamespot.com/forums/api-developers-2334/searches-not-working-correctly-from-comicvine-scra-1922307/#2)

**Comment by Tec445** [comment]
I'm experiencing this issue as well. Ex: If I search for Black Hammer I get a list of the issues and below there is a list of the TPBs. But when I search for the TPB "Black Hammer Secret Origins" I get "No matches" Also If I search "Final Crisis" a list of the main series shows up, but If I search for any of the spin-offs I get "no matches"

**Comment by davide-romanini** [comment]
It effectively seems a ComicVine problem. Hope it's just temporary.

**Comment by davide-romanini** [comment]
It seems [confirmed as a CV problem](https://comicvine.gamespot.com/forums/api-developers-2334/searches-not-working-correctly-from-comicvine-scra-1922307/?page=1#js-message-19767215). Closing.

**Comment by tombs007** [comment]
I've been tinkering a bit with the code and been able to improve my search results. In comicapi/utils.py I commented out line:

line 135     newText = newText.replace("-", " ")

It seems that the current incarnation of CV searches are looking for or expecting "-", ":", and possibly other characters as well.

@gclicon
